"""empty message

Revision ID: feb38eaa262b
Revises: 6d3d1c849abb
Create Date: 2018-10-22 17:16:28.954168

"""

# revision identifiers, used by Alembic.
revision = 'feb38eaa262b'
down_revision = '6d3d1c849abb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_connection',
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('billing_id', sa.String(), nullable=True),
    sa.Column('billing_info', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.email'], ),
    sa.PrimaryKeyConstraint('owner', 'service')
    )
    op.create_table('service_connection',
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.email'], ),
    sa.PrimaryKeyConstraint('owner', 'service')
    )
    op.drop_table('sessions')
    op.add_column('user', sa.Column('created', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('payment_active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('phone_verified', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('stale', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stale')
    op.drop_column('user', 'phone_verified')
    op.drop_column('user', 'payment_active')
    op.drop_column('user', 'email_verified')
    op.drop_column('user', 'created')
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.Column('expiry', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.drop_table('service_connection')
    op.drop_table('billing_connection')
    # ### end Alembic commands ###
